### ISSUE TITLE
what wrong

### ISSUE THREAD

**Issue by liuseen-l** [redfox-mx/vite-lit-css#1]
Uncaught TypeError: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Failed to convert value to 'CSSStyleSheet'.

```js
import styles from './style/index.css?inline'
@customElement('nova-button')
export class NovaButton extends LitElement {
  @property({ type: Number })
  count = 1

  static styles = [styles] as any as CSSResult
  constructor() {
    super()
  }

  render() {
    return html`
        <button @click=${this._onClick} part="button">
          count is ${this.count}
        </button>
    `
  }

  private _onClick() {
    this.count++
  }
}


```

**Comment by redfox-mx** [comment]
Hi! You should use '?lit' query instead for lit styles, inline styles are handled like narmal strings by vite.

```ts
import styles from './style/index.css?lit'
```

Optionally, you should use alpha release since some build issues were fixed. BTW, Unfortunately I dont have enough feedback to release a major version. And 0.x.x version are not suitable for production products.
